const mongoose = require('mongoose');

// One row per user, per day, per insight type — generated by the nightly cron
// (see services/dailyInsightService.js) from that day's logged data.
//
// Two dates matter here and they are deliberately different:
//   sourceDate  — the day whose data the insight was built from (8 Aug)
//   insightDate — the day the user sees it on, always sourceDate + 1 (9 Aug)
// The cron runs at 23:59 IST on the 8th, so the insight is already waiting
// when the user opens the app on the 9th and reads "yesterday you did X...".
const dailyInsightSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

  insightDate: { type: String, required: true }, // 'YYYY-MM-DD' IST — the display day
  sourceDate: { type: String, required: true },  // 'YYYY-MM-DD' IST — the day analysed

  insightType: {
    type: String,
    enum: ['activity', 'medical_report'],
    required: true,
  },

  title: { type: String, required: true },       // short headline, ~6 words
  description: { type: String, required: true }, // the encouraging "yesterday → today" body
  summary: { type: String, required: true },     // one-line takeaway for cards/notifications

  // What the model was actually shown. Kept so a bad insight can be debugged
  // without re-querying a day's worth of logs that may since have changed.
  dataSnapshot: { type: mongoose.Schema.Types.Mixed, default: {} },

  model: { type: String },                       // which free model produced it
  seen: { type: Boolean, default: false },
  seenAt: { type: Date, default: null },
}, { timestamps: true });

// A re-run of the cron (or a manual backfill) must update, never duplicate.
dailyInsightSchema.index({ userId: 1, insightDate: 1, insightType: 1 }, { unique: true });
dailyInsightSchema.index({ userId: 1, insightDate: -1 });

module.exports = mongoose.model('DailyInsight', dailyInsightSchema);
